# Generated by Django 5.0.4 on 2024-06-22 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telemovel', models.CharField(max_length=80)),
                ('nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=80)),
                ('codigo_postal', models.CharField(max_length=80)),
                ('documento', models.FileField(upload_to='pdfs/')),
                ('documento2', models.FileField(upload_to='pdfs2/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
