# Generated by Django 5.0.4 on 2024-05-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_user_details_delete_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='dcoumeneto2',
            new_name='documento2',
        ),
    ]
